### ISSUE TITLE
Add Functionality to provide length of matched strings

### ISSUE THREAD

**Issue by smutzc** [plusvic/yara#110]
This is a feature request.

I'm interested in building signatures that could be more efficient if I had the ability to know the length of matched strings. This is obviously only interesting when a wildcard or jump is used and the length of the matched strings is not fixed. One place where I would use this would be to improve the efficiency of conditions which I have used to replace use of back references.

For example, you could have Xa[1] represent either the offset of last char of the match or the length of the matched string $a. I think it's better to return the length of the match than the offset of the end of the string, but you can convert between the two using addition or subtraction of @a[1].

I don't have a strong recommendation on the symbol used to denote this ("X" above). It seems like "#" is already used and may not be available for this.

**Comment by plusvic** [comment]
Implemented in 38f5f8fbfb6bcac6649c7df93f8ee884b08e4801
