### ISSUE TITLE
Add ability to use filename/path in signature

### ISSUE THREAD

**Issue by vanvleet** [plusvic/yara#202]
Feature request:  It would be great if Yara had the ability to match file names and paths.  Sometimes the name or location of a file is a reliable signature for malware.  Thanks!

**Comment by plusvic** [comment]
YARA can be used in other contexts where the file name is not known, it's oriented to detect files based on their content, not in other environmental variables. You could always pass an external variable with the file name and use it from your rules.

**Comment by vanvleet** [comment]
Hey Victor, thanks for the reply.  How do you pass an external variable...
that's not something I was aware of?  Did I miss it in the documentation
(if so, just send me a "RTFM!")  :o)

On Tue, Feb 10, 2015 at 4:21 AM, Victor M. Alvarez <notifications@github.com

**Comment by plusvic** [comment]
If using the command-line interface you should use the -d argument. But it doesn't make sense if what you want is scanning a whole directory and match files with a certain name. In that case you could write a python script to traverse the directory and use yara-python to scan each individual file, passing the filename as an external variable with the "external" argument in the "match" method. 

See http://yara.readthedocs.org/en/v3.3.0/yarapython.html

**Comment by Neo23x0** [comment]
Here is a powershell example:
https://www.bsk-consulting.de/2014/08/28/scan-system-files-manipulations-yara-inverse-matching-22/

**Comment by 2d4d** [comment]
@plusvic The drawback of passing the filename via -d is that you have to start a yara process for each individual file. How about a module like "file_metadata" which provides the filename where it's available? 

There are lots of uses for it e.g.:
- files which are procdump but not called procdump*exe
- executables with unusual extensions
- mildly suspicious files which are very suspicious if they reside in certain paths

It's proven to be valuable in e.g. https://github.com/Neo23x0/Loki which has lots of rules which use it:
63 use filename
5 use extension
21 use filepath

From https://github.com/Neo23x0/signature-base/tree/master/yara in files:
general_cloaking.yar
generic_anomalies.yar
thor_inverse_matches.yar
yara_mixed_ext_vars.yar

Would be just few lines of code and save all projects which use yara to look for malware on live filesystems or forensic images from the hassle to reinvent the wheel in combining the files content with the metadata. With -d this might end up in the way, that x different scanners use x different naming conventions and rules would have to be converted. Better make one module for it and there would be one standard. And there would be no performance impact of starting 100.000 yara processes for scanning 100.000 files.

**Comment by JPaulMora** [comment]
Bumping thread, filename match is basically how I clean wordpress sites manually.
