### ISSUE TITLE
Unicode - CreateFile

### ISSUE THREAD

**Issue by bergeret** [plusvic/yara#205]
I'm compiling on windows, and my project is fully unicode.
Could you apply this fix, to avoid calling the wrong function as you force the filename to be "char*".

diff --git a/libyara/filemap.c b/libyara/filemap.c
index 4b6f516..a22f6fd 100755
--- a/libyara/filemap.c
+++ b/libyara/filemap.c
@@ -43,7 +43,7 @@ YR_API int yr_filemap_map(
   if (file_path == NULL)
     return ERROR_INVALID_ARGUMENT;

-  pmapped_file->file = CreateFile(
+  pmapped_file->file = CreateFileA(
       file_path,
       GENERIC_READ,

**Comment by plusvic** [comment]
Fixed in 0173d3a925f0c23d36d1912066a2d4d9cfc10ffa
