### ISSUE TITLE
Hash module not found in the official Windows binaries

### ISSUE THREAD

**Issue by ricardo-dias** [plusvic/yara#217]
Official Windows binaries returns "unknown module" when importing "hash" module.

**Comment by jovimon** [comment]
Same problem here :(

**Comment by ricardo-dias** [comment]
A similar problem happens in the yara-python modules for windows. For example:
---
import "hash" 
rule myhash { condition: hash.md5(0, filesize) == "feba6c919e3797e7778e8f2e85fa033d" }
---
returns:
invalid field name "md5"

**Comment by plusvic** [comment]
Fixed in version 3.3.0
