### ISSUE TITLE
Custom user data in compiler callback

### ISSUE THREAD

**Issue by bfosterjr** [plusvic/yara#220]
Please add a user_data field to the the compiler callback (similar to the scanning callback).

**Comment by hillu** [comment]
I'd like to second this: Without the `user_data` field, I don't see
any (thread-safe) way to get detailed error information in my go-yara
bindings.

**Comment by plusvic** [comment]
Fixed in b90e8b5283b27e1158cf2f59faf15edc4a0d107b
