### ISSUE TITLE
-r not working in yara 3.0?

### ISSUE THREAD

**Issue by johnrandomsmith2** [plusvic/yara#230]
I installed yara on OS X w/ brew install yara per the documentation

I have a sig that I use like
yara sig.rule -r /Volumes/folder1/folder2/
and it finds matches on files in the folder
but when I then do
yara sig.rule -r /Volumes/folder1/
it finds no matches

thoughts?

**Comment by johnrandomsmith2** [comment]
I now think this may be some OS X specific issue, because yara 2.1 on Ubuntu seems to exhibit the correct behavior (On Mac OS X yara just returns immediately)

**Comment by wxsBSD** [comment]
I do ally development for YARA on OS X. I can test this out in a few hours.

**Comment by wxsBSD** [comment]
I can't duplicate this on my OS X machine running the latest from master branch.

**Comment by plusvic** [comment]
I found the cause of this problem. While iterating over a directory YARA ignores files links to avoid entering in link loops. It turns out that the /Volumes directory in Mac OS X contains just links to other directories which are ignored.
