### ISSUE TITLE
Any reason not to support more IMAGE_FILE_MACHINE types?

### ISSUE THREAD

**Issue by wxsBSD** [plusvic/yara#231]
This is more of a point of discussion, but I thought I would bring it up to get input.

I've got a PE here (5b3e80c8b87bf96c7a13172619209502) I was using to test out my resource name stuff when I found it YARA would not parse it. I dug into it and found out it specifies a Machine field in the FileHeader (pe_header->FileHeader.Machine) of IMAGE_FILE_MACHINE_ARMNT (0x1c4). Adding this to the checks in pe_get_header() fixed the problem.

I'm curious if you would be open to expanding this check to include all the IMAGE_FILE_MACHINE constants. I have not seen anything in the documentation which says the specification changes based upon any of these values, so from that standpoint it should be safe.

I will hunt through my collection of PE files and see if any of them have something besides IMAGE_FILE_MACHINE_I386 or IMAGE_FILE_MACHINE_AMD64, and make sure the parser handles them correctly if I add them to the list.

**Comment by plusvic** [comment]
Great, I like the idea of parsing more PE types. I was conservative and accepted only I386 and AMD64 because I didn't know if other types had differences. But let's open it and accept more platforms.

**Comment by wxsBSD** [comment]
Ok! I'll get a patch ready by the end of today.

**Comment by plusvic** [comment]
Fixed in eccb4341899226f0670d182d6f0a5f9a55e76ac7
