### ISSUE TITLE
MAX_STRING_MATCHES exceeded without error

### ISSUE THREAD

**Issue by marnao** [plusvic/yara#237]
Sample fix below is for yara v2.1 as that's the version we're currently using. We did confirm the bug still exists in 3.2.

To demonstrate:

Two strings, one fixed and one with a wildcard pattern.

	$ cat fixed.yara
	rule test
	{
	    strings:
	        $ = { 41 41 41 41 }
	    condition:
	        any of them
	}

	$ cat wildcard.yara
	rule wildcard
	{
	    strings:
	        $ = { 41 4? 41 41 }
	    condition:
	        any of them
	}

Generate a 5MB file of all A characters.

	$ perl -e 'print "A"x5000000' > large.txt

Version of yara being tested, and default compile-time values.

	$ yara -v
	yara 2.1

	$ grep MAX_STRING_MATCHES yara-2.1.0/libyara/yara.h
	#define MAX_STRING_MATCHES  1000000

	$ grep ERROR_TOO_MANY_MATCHES yara-2.1.0/libyara/yara.h
	#define ERROR_TOO_MANY_MATCHES                  30

The signatures are too noisy.  The fixed string generates an error, the wildcard unintentionally scans to end of file.

	$ time yara fixed.yara large.txt
	Error scanning large.txt: internal error: 30
	
	real    0m0.208s
	user    0m0.173s
	sys     0m0.034s

	$ time yara wildcard.yara large.txt
	wildcard large.txt			<-- no error, end result is signature match
	
	real    0m0.840s
	user    0m0.762s
	sys     0m0.077s

Adding in a diagnostic to print the number of hits as the scan proceeds shows that the wildcard stops counting total hits at 1M, but keeps scanning and processing additional hits (without incrementing the counter), using some additional resources but more importantly not informing the user of a problem with the signature.

	.../yara-2.1.0-diag/bin/yara fixed.yara large.txt
	debug: match count = 0
	debug: match count = 1
	debug: match count = 2
	debug: match count = 3
	...
	debug: match count = 999997
	debug: match count = 999998
	debug: match count = 999999
	debug: match count = 1000000
	Error scanning large.txt: internal error: 30	<-- fixed signature result
	$

	.../yara-2.1.0-diag/bin/yara wildcard.yara large.txt
	debug: match count = 0
	debug: match count = 1
	debug: match count = 2
	debug: match count = 3
	...
	debug: match count = 999996
	debug: match count = 999997
	debug: match count = 999998
	debug: match count = 999999
	debug: match count = 1000000
	debug: match count = 1000000
	debug: match count = 1000000
	debug: match count = 1000000
	*** and so on ~4 million more times until end of scan file reached ***
	wildcard large.txt						<-- no error, end result is signature match

Here is a proposed patch for yara 2.1.0 that makes the behavior more consistent:

$ cat yara-2.1.0-too-many.patch
--- yara-2.1.0/libyara/rules.c.orig     2014-03-05 11:14:32.000000000 +0000
+++ yara-2.1.0/libyara/rules.c  2015-01-20 21:59:53.414303089 +0000
@@ -181,6 +181,7 @@
   int matches;
   int stop;
   int increment;
+  int rcode;

   increment = flags & RE_FLAGS_BACKWARDS ? -1 : 1;

@@ -288,11 +289,13 @@
       {
         if (flags & RE_FLAGS_EXHAUSTIVE)
         {
-          callback(
+          rcode = callback(
             flags & RE_FLAGS_BACKWARDS ? current_input + 1 : input,
             matches,
             flags,
             callback_args);
+          if (rcode == ERROR_TOO_MANY_MATCHES)
+            return -4;
           stop = TRUE;
         }
         else
@@ -701,6 +704,8 @@
       return ERROR_INSUFICIENT_MEMORY;
     case -3:
       return ERROR_INTERNAL_FATAL_ERROR;
+    case -4:
+      return ERROR_TOO_MANY_MATCHES;
   }

   if (forward_matches == 0 && ac_match->backward_code == NULL)
@@ -729,6 +734,9 @@

     if (backward_matches == -3)
       return ERROR_INTERNAL_FATAL_ERROR;
+
+    if (backward_matches == -4)
+      return ERROR_TOO_MANY_MATCHES;
   }
   else
   {
[EOF]

And when yara is built with the patch:

	.../yara-2.1.0-patched/bin/yara wildcard.yara large.txt
	debug: match count = 0
	debug: match count = 1
	debug: match count = 2
	debug: match count = 3
	...
	debug: match count = 999996
	debug: match count = 999997
	debug: match count = 999998
	debug: match count = 999999
	debug: match count = 1000000
	Error scanning large.txt: internal error: 30	<-- same as previously seen with fixed signature
	$

Thanks for taking a look!

**Comment by plusvic** [comment]
Fixed in 7af17060ab516e9af82a69a91715b36080a62472
