### ISSUE TITLE
Python3 cannot deal with non-UTF-8-compliant strings in callback.

### ISSUE THREAD

**Issue by hillu** [plusvic/yara#240]
A successful match for a rule where meta-variables or tags contain non-UTF-8-compliant byte sequences will lead to a crash of yara-python under Python 3.

**Comment by hillu** [comment]
The specific commit is https://github.com/hillu/yara/commit/09e743f473536af3fcdcd8d04c9b4f4e21b76611

**Comment by plusvic** [comment]
Instead of applying this patch I'll address the root cause of the problem, which is that YARA doesn't validate the strings to make sure they are UTF-8. See issue #248.
