### ISSUE TITLE
PE module imphash calculation is wrong

### ISSUE THREAD

**Issue by joesecurity** [plusvic/yara#242]
I think the issue is at:

 MD5_Update(&ctx, final_name, final_name_len);

Should be:

 MD5_Update(&ctx, final_name, final_name_len -1 );

Otherwise you hash also \0

**Comment by wxsBSD** [comment]
Are you using the latest release? There is a bug that happened during a refactoring of the imphash code which was fixed after the release was made. See this for more information:

https://github.com/plusvic/yara/pull/199

**Comment by joesecurity** [comment]
I am using the latest release, thanks for pointing it out!

**Comment by wxsBSD** [comment]
This can be closed now that 3.3.0 is out.
