### ISSUE TITLE
PE Module 32BIT_MACHINE imagecharacteristic syntax error

### ISSUE THREAD

**Issue by joesecurity** [plusvic/yara#243]
I am using release 3.2.0, example rule:

import "pe"

rule test {
	condition:
		pe.characteristics & pe.32BIT_MACHINE
}

Syntax error: rule.yara(5): error: syntax error, unexpected _NUMBER_, expecting _IDENTIFIER_

**Comment by Neo23x0** [comment]
Try:

import "pe"

rule test {
condition:
pe.characteristics and pe.machine == pe.MACHINE_I386
}


On Tue, Jan 27, 2015 at 2:54 PM, Joe Security <notifications@github.com>
wrote:

> import "pe"
>
> rule test {
> condition:
> pe.characteristics & pe.32BIT_MACHINE
> }
>




-- 
Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

PGP Key:
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM
Key ID:
FE04247D50D1ACC855CB FD26 19E9 BF9E 78C1  D582 FE04 247D 50D1 ACC8

**Comment by wxsBSD** [comment]
Sadly, Florian I believe your suggestion is, at best, a partial solution. It will not recognize 32bit files for non x86 architectures. I've currently got an open PR that would make this kind of rule very false-negative prone.

I'm currently digging into why this is not working like I would expect. The ```pe.32BIT_MACHINE``` is not being recognized properly by the compiler and I'm not sure why.

**Comment by wxsBSD** [comment]
If all you care about is that the Machine field is pe.MACHINE_I386 you can use that but it will not find 32bit files for other architectures. If you only care that it is a 32bit file but don't care what architecture you should be able to use the bitmask like you are describing, but sadly that is broken and I have figured out why.

The name needs to be changed from 32BIT_MACHINE to something else that does not start with a number. I'll get a PR up for Victor to look at.
