### ISSUE TITLE
Yara 2.x-3.x+ all crash, internal error 25, on large rules (example inlined)

### ISSUE THREAD

**Issue by ckane** [plusvic/yara#255]
We auto-generate numerous yara rules with a high volume of strings in order to utilize yara as a large-scale pattern-matching and cluster-identifying tool. All versions above yara 1.7 seem to crash on large rules with this "internal error: 25". Because of this bug, we cannot move from yara 1.7 for our rulesets without sacrificing this project.

I have an example of an offending rul (this one built with junk data) to my github repo at:
https://github.com/ckane/yara23-bug-rules

**Comment by wxsBSD** [comment]
You're overflowing the stack used by YARA. You can work around it by bumping STACK_SIZE in libyara/exec.c to a much bigger number. I used 85000, just because it was bigger than the number of strings you have. Just a quick read through the code, so I could be completely wrong here, but I think when you use 'any of them' in a condition it will push every non-chained string onto the stack. Since the stack size is much smaller than the number of things being pushed you get the overflow.

As to a possible better answer than bumping STACK_SIZE, I really don't know off the top of my head.

**Comment by plusvic** [comment]
Wesley is right, when you use "any of them" a reference to each string is pushed in the stack, with that many strings your overflowing the stack. One solution is setting a higher STACK_SIZE as suggested, another one is splitting this huge rule in multiple smaller rules.

I'm going to mark this as "won't fix" because this is not an actual bug. You're just hitting an internal limit.

**Comment by ckane** [comment]
For my particular application, splitting the strings into separate rules is likely a no-go. I'll try increasing the stack size, as I have "all the RAM" on the environment doing the work, and see what that nets me. Just curious however, are you aware as to whether there's a ceiling to the stack size? In one case I am seeing over 200,000+ strings in a single rule.

From your description of the implementation, it sounds to me like this is a per-rule limit, though? Is there perhaps a way to provide a command-line argument to modify this at run-time?

**Comment by ckane** [comment]
Ok I set the stack size to 800000 and that seems to work. However, if I bump it to 1048576 (my first attempt before dropping incrementally to lower sizes), I get a seg fault:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000043159b in yr_execute_code (rules=<error reading variable: Cannot access memory at address 0x7fffff7fd598>, 
    context=<error reading variable: Cannot access memory at address 0x7fffff7fd590>, 
    timeout=<error reading variable: Cannot access memory at address 0x7fffff7fd58c>, 
    start_time=<error reading variable: Cannot access memory at address 0x7fffff7fd580>) at exec.c:130
130     {
(gdb) bt
#0  0x000000000043159b in yr_execute_code (rules=<error reading variable: Cannot access memory at address 0x7fffff7fd598>, 
    context=<error reading variable: Cannot access memory at address 0x7fffff7fd590>, 
    timeout=<error reading variable: Cannot access memory at address 0x7fffff7fd58c>, 
    start_time=<error reading variable: Cannot access memory at address 0x7fffff7fd580>) at exec.c:130
#1  0x0000000000413f19 in yr_rules_scan_mem_blocks (rules=0x655010, block=0x0, flags=0, callback=0x403c99 <callback>, user_data=0x7fffffffe17d, timeout=1000000)
    at rules.c:425
#2  0x0000000000414189 in yr_rules_scan_mem (rules=0x655010, buffer=0x7ffff7f2e000 "\177ELF\002\001\001", buffer_size=692295, flags=0, 
    callback=0x403c99 <callback>, user_data=0x7fffffffe17d, timeout=1000000) at rules.c:515
#3  0x00000000004141eb in yr_rules_scan_file (rules=0x655010, filename=0x7fffffffe17d "yara", flags=0, callback=0x403c99 <callback>, user_data=0x7fffffffe17d, 
    timeout=1000000) at rules.c:540
#4  0x0000000000404880 in main (argc=2, argv=0x7fffffffde98) at yara.c:1043
(gdb) 
```
So for the time being it would seem that the lower number will work for my purposes, although the size of my dataset only increases with every passing month, so at some point I'll probably end up hitting the wall again.

Thanks for the quick response and work-around.

**Comment by wxsBSD** [comment]
I know this is a wontfix but there is something about that segfault that is interesting. I went ahead and duplicated this on an OS X (10.10.2) machine. I then went looking for what would cause it and didn't come up with anything in the source code. Stepping through it in a debugger on OS X I noticed this is the start of the disassembly for yr_execute_code:

```
(lldb) dis -F intel -c 11
yara`yr_execute_code at exec.c:130:
-> 0x10002af60:  push   rbp
   0x10002af61:  mov    rbp, rsp
   0x10002af64:  sub    rsp, 0x8005a0
   0x10002af6b:  mov    rax, qword ptr [rip + 0x2e08e] ; (void *)0x00007fff7ac96070: __stack_chk_guard
   0x10002af72:  mov    rax, qword ptr [rax]
   0x10002af75:  mov    qword ptr [rbp - 0x8], rax
   0x10002af79:  mov    qword ptr [rbp - 0x8004b8], rdi
   0x10002af80:  mov    qword ptr [rbp - 0x8004c0], rsi
   0x10002af87:  mov    dword ptr [rbp - 0x8004c4], edx
   0x10002af8d:  mov    qword ptr [rbp - 0x8004d0], rcx
   0x10002af94:  mov    dword ptr [rbp - 0x8004d4], 0x0
```

The crash happens executing the instruction at 0x10002af79.

I then tried to reproduce this on a Linux machine and two FreeBSD machines. The crash did not happen on one of my FreeBSD machines, but did on the Linux and the other FreeBSD machine.

This is the disassembly from yr_execute_code on the Linux machine:

```
(gdb) disass
Dump of assembler code for function yr_execute_code:
   0x0000000000430fc8 <+0>:	push   rbp
   0x0000000000430fc9 <+1>:	mov    rbp,rsp
   0x0000000000430fcc <+4>:	push   rbx
   0x0000000000430fcd <+5>:	sub    rsp,0x800538
=> 0x0000000000430fd4 <+12>:	mov    QWORD PTR [rbp-0x800518],rdi
   0x0000000000430fdb <+19>:	mov    QWORD PTR [rbp-0x800520],rsi
   0x0000000000430fe2 <+26>:	mov    DWORD PTR [rbp-0x800524],edx
   0x0000000000430fe8 <+32>:	mov    QWORD PTR [rbp-0x800530],rcx
   0x0000000000430fef <+39>:	mov    DWORD PTR [rbp-0x800510],0x0
```

And this is the output from yr_execute_code on the *NOT WORKING* FreeBSD machine (this one crashes at 0x439333):

```
(gdb) disass yr_execute_code
Dump of assembler code for function yr_execute_code:
0x0000000000439300 <yr_execute_code+0>: push   rbp
0x0000000000439301 <yr_execute_code+1>: mov    rbp,rsp
0x0000000000439304 <yr_execute_code+4>: sub    rsp,0x800580
0x000000000043930b <yr_execute_code+11>:        mov    QWORD PTR [rbp-0x10],rdi
0x000000000043930f <yr_execute_code+15>:        mov    QWORD PTR [rbp-0x18],rsi
0x0000000000439313 <yr_execute_code+19>:        mov    DWORD PTR [rbp-0x1c],edx
0x0000000000439316 <yr_execute_code+22>:        mov    QWORD PTR [rbp-0x28],rcx
0x000000000043931a <yr_execute_code+26>:        mov    DWORD PTR [rbp-0x4b4],0x0
0x0000000000439324 <yr_execute_code+36>:        mov    rcx,QWORD PTR [rbp-0x10]
0x0000000000439328 <yr_execute_code+40>:        mov    rcx,QWORD PTR [rcx+0x8]
0x000000000043932c <yr_execute_code+44>:        mov    QWORD PTR [rbp-0x4c0],rcx
0x0000000000439333 <yr_execute_code+51>:        mov    DWORD PTR [rbp-0x800514],0x0
```

The *WORKING* FreeBSD machine:

```
(gdb) disass
Dump of assembler code for function yr_execute_code:
0x000000000043a320 <yr_execute_code+0>:	push   rbp
0x000000000043a321 <yr_execute_code+1>:	mov    rbp,rsp
0x000000000043a324 <yr_execute_code+4>:	sub    rsp,0x800580
0x000000000043a32b <yr_execute_code+11>:	mov    QWORD PTR [rbp-0x10],rdi
0x000000000043a32f <yr_execute_code+15>:	mov    QWORD PTR [rbp-0x18],rsi
0x000000000043a333 <yr_execute_code+19>:	mov    DWORD PTR [rbp-0x1c],edx
0x000000000043a336 <yr_execute_code+22>:	mov    QWORD PTR [rbp-0x28],rcx
0x000000000043a33a <yr_execute_code+26>:	mov    DWORD PTR [rbp-0x4b4],0x0
```

Could this be some weird compiler issue causing it to incorrectly calculate the offset from rbp? I'm clearly in over my head, but I thought I would at least share what I've found. Here's the information for each machine:

OS X:
```
wxs@psh yara % gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
wxs@psh yara %
```

Linux:
```
wxs@foo:~/yara$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
wxs@foo:~/yara$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

wxs@foo:~/yara$
```

FreeBSD (NOT WORKING):
```
wxs@syn yara % uname -r
10.1-RELEASE-p5
wxs@syn yara % cc -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix
Selected GCC installation: 
wxs@syn yara %
```

FreeBSD (WORKING):
```
wxs@ack yara % uname -r 
11.0-CURRENT
wxs@ack yara % cc -v
FreeBSD clang version 3.5.1 (tags/RELEASE_351/final 225668) 20150115
Target: x86_64-unknown-freebsd11.0
Thread model: posix
wxs@ack yara %
```

**Comment by ckane** [comment]
So I suspect this has something to do with how the compiler allocates space on the stack. In the yr_execute_code(...) function, stack is a local stack-allocated array variable sized at STACK_SIZE*sizeof(union STACK_ITEM). I wonder if this is a matter of one of the stack-smashing-protections or event RLIMIT_STACK getting in the way...though it is an odd way to fail.

I tried -fno-stack-protector and it still failed.

Then I just converted:
```
union STACK_ITEM stack[STACK_SIZE];
```
To:
```
union STACK_ITEM *stack;
```

in order to allocate it on the heap instead (and of course added free(stack) in the places where it belongs in the function. Making that change makes the crash go away, and I doubt that there's any significant performance penalty. On a good note, as well, that change probably could eliminate a potential future (but untested) vulnerability vector for a piece of software that's widely known to be adopted by the world's security community, and who's purpose is to flow "untrusted" and "suspected attack" data through a complicated pipeline of C code.

**Comment by ckane** [comment]
That would have the additional benefit of enabling the stack-size to be converted into a run-time tunable.

**Comment by ckane** [comment]
```
--- libyara/exec.c.old  2015-02-19 23:33:52.494000000 -0500
+++ libyara/exec.c      2015-02-19 23:34:06.263000000 -0500
@@ -133,7 +133,7 @@
   int32_t sp = 0;
   uint8_t* ip = rules->code_start;
 
-  union STACK_ITEM stack[STACK_SIZE];
+  union STACK_ITEM *stack;
   union STACK_ITEM r1;
   union STACK_ITEM r2;
   union STACK_ITEM r3;
@@ -156,6 +156,8 @@
   clock_t start = clock();
   #endif
 
+  stack = calloc(STACK_SIZE, sizeof(union STACK_ITEM));
+
   while(1)
   {
     switch(*ip)
@@ -164,6 +166,7 @@
         // When the halt instruction is reached the stack
         // should be empty.
         assert(sp == 0);
+        free(stack);
         return ERROR_SUCCESS;
 
       case OP_PUSH:
@@ -1043,8 +1046,10 @@
 
       if (++cycle == 10)
       {
-        if (difftime(time(NULL), start_time) > timeout)
+        if (difftime(time(NULL), start_time) > timeout) {
+          free(stack);
           return ERROR_SCAN_TIMEOUT;
+        }
 
         cycle = 0;
       }
@@ -1056,5 +1061,6 @@
   // After executing the code the stack should be empty.
   assert(sp == 0);
 
+  free(stack);
   return ERROR_SUCCESS;
 }
```

**Comment by wxsBSD** [comment]
I was thinking something similar (move the stack off the stack). If you are going to send a PR you will want to use yr_alloc and yr_free though. I have no clue what Victor will say about this though.

**Comment by ckane** [comment]
Yeah I'll run some tests on my end and use the yr_* versions like you suggested. Might also take a stab at cmdline option... all dependent upon what other work I need to procrastinate on.

**Comment by ckane** [comment]
I'd probably suggest moving stack into the YR_CONTEXT struct, in that event and initialize it in libyara/rules.c where needed, enabling fewer malloc/free cycles and a cleaner approach to memory management than my first version above. Intuitively the "stack" following around the execution context would probably be the expected behavior to a new observer.

**Comment by plusvic** [comment]
I think it's a good idea to use dynamically allocated memory for the stack. Maintaining the pointer in YR_CONTEXT as ckane suggests seems like a elegant solution.

**Comment by ckane** [comment]
Cool - I'll work on a patch this weekend, time permitting

**Comment by n0way0ut** [comment]
is the weekend terminated? or this issue is fixed in another way? I still have it today.

**Comment by wxsBSD** [comment]
I think it was merged in. You will need to provide more context (preferably in another issue) with what you're seeing. Please include a rule which triggers the problem for you.

You may also want to look at the -k argument to yara too, as I think that is directly related to the work @ckane did in this area.
