### ISSUE TITLE
Effects of different return values from callback never get explained

### ISSUE THREAD

**Issue by axqd** [plusvic/yara#270]
Documents for C API should mention the effects of different return values from callback function of yr_rules_scan_xxx(). 
It's very important information to use callback.

 1. Return CALLBACK_CONTINUE to do 'continue';
 1. Return CALLBACK_ABORT to do 'break';
 1. Return CALLBACK_ERROR to 'error' out.

**Comment by plusvic** [comment]
Fixed in fc704b684b1c678a3c3890421f4e268497eca2b8
