### ISSUE TITLE
Permissions in tarball

### ISSUE THREAD

**Issue by fabaff** [plusvic/yara#273]
Inside the tarball a couple of file have wired permission:

- libyara/filemap.c
- libyara/include/yara/filemap.h
- args.c
- args.h

This is not an issue for the RPM package (I fix this inside the spec file) but it would be nice if this get fixed in a future release. Thanks.

**Comment by plusvic** [comment]
Fixed in 6bd27e0512634ac373d5f2911837dfe208d472ed
