### ISSUE TITLE
'in' operator possible bug

### ISSUE THREAD

**Issue by pertesi** [plusvic/yara#290]
The 'in' operator seems doesn't work in the right mode, by launching this example rule:
#######################
rule InExample
{
    strings:
        $a = {00 00 00}
       $b = {65 00 73 00}

    condition:
       $a in (0..100) and $b in (100..filesize)
}
#################################

The output look like:
0x5:$a: 00 00 00 
0x9:$a: 00 00 00 
0x11:$a: 00 00 00
*
0x1b8:$a: 00 00 00 
0x1b9:$a: 00 00 00 
0x1ba:$a: 00 00 00
*
0x88738:$a: 00 00 00 
0x88739:$a: 00 00 00 
0x8781a:$b: 65 00 73 00 
0x87830:$b: 65 00 73 00 
0x885d8:$b: 65 00 73 00 

yara match rule $a not only in 0..100 range but in all file.

yara 3.3.0, SO ubuntu 14.10 32bit.

**Comment by plusvic** [comment]
This is not actually a bug. All the matches for a given string are always printed, even if they are outside the range specified in the condition, or the condition is not satisfied for any other reason. Think in the condition:  not $a. Should $a be printed if present in the file?

**Comment by pertesi** [comment]
Ok, thank you so much for the answer.


2015-03-24 11:00 GMT+01:00 Victor M. Alvarez <notifications@github.com>:
