### ISSUE TITLE
Detect when Yara rules where compiled with an older version of the tool

### ISSUE THREAD

**Issue by JusticeRage** [plusvic/yara#292]
When using compiled rules (.yarac), I found out that Yara has no backward compatibility.
This is not a problem in itself, but would it be possible to detect when the old compiled rules aren't compatible in order to exit gracefully instead of crashing?

Everytime I encountered the problem, the crash occurred at [exec.c:199](https://github.com/plusvic/yara/blob/master/libyara/exec.c#L199).

**Comment by plusvic** [comment]
Fixed in 85023938793fa658cf8bfffbbc929657f04910ca

**Comment by JusticeRage** [comment]
Great !
Thank you very much!
