### ISSUE TITLE
Using "pe" module on certain files causes hang

### ISSUE THREAD

**Issue by arbor-jjones** [plusvic/yara#297]
When run on many files, I am experiencing hangs when running on files with rules using the "pe" module.

Example files:
Sha256: 391a1b5c0e802abef56c3e3a3cc849c395a23d0652fbb47dc5c3a5543103330c
Sha256: 08e6cdc3d5bdc60d952b52530a1e3b46cd4666f4641023dfa9a4a1c95298af87

GDB backtrace after issuing ctrl-c on      08e6cdc3d5bdc60d952b52530a1e3b46cd4666f4641023dfa9a4a1c95298af87:

    0x0000000000416e93 in strcmp_w (w_str=0x7ffff7fe6380 "i", str=0x43baee "ileInfo",
    str@entry=0x43bae7 "StringFileInfo") at strutils.c:175
    175	  while (*w_str != 0 && *str != 0 && *w_str == *str)
    (gdb) where
    #0  0x0000000000416e93 in strcmp_w (w_str=0x7ffff7fe6380 "i", str=0x43baee "ileInfo",
        str@entry=0x43bae7 "StringFileInfo") at strutils.c:175
    #1  0x000000000041ce88 in pe_parse_version_info (rsrc_data=rsrc_data@entry=0x7ffff7fe62c0,
        pe=pe@entry=0x708bb0) at modules/pe.c:639
    #2  0x000000000041d1d1 in pe_collect_resources (rsrc_data=0x7ffff7fe62c0, rsrc_type=16, rsrc_id=1,
        rsrc_language=1033, type_string=<optimized out>, name_string=<optimized out>,
        lang_string=<optimized out>, pe=0x708bb0) at modules/pe.c:769
    #3  0x000000000041ca88 in _pe_iterate_resources (pe=0x708bb0, resource_dir=0x43baee,
        rsrc_data=0x7ffff7fe6200 "", rsrc_tree_level=2, type=0x0, id=0x2c000, language=0x7ffffffdd9a0,
        type_string=0x0, name_string=0x0, lang_string=0x0, callback=0x41d000 <pe_collect_resources>,
        callback_data=0x708bb0) at modules/pe.c:510
    #4  0x000000000041ca15 in _pe_iterate_resources (pe=0x708bb0, resource_dir=0x43baee,
        rsrc_data=0x7ffff7fe6200 "", rsrc_tree_level=1, type=0x0, id=0x2c000, language=0x7ffffffdd9a0,
        type_string=0x0, name_string=0x0, lang_string=0x0, callback=0x41d000 <pe_collect_resources>,
        callback_data=0x708bb0) at modules/pe.c:485
    #5  0x000000000041ca15 in _pe_iterate_resources (pe=0x708bb0, resource_dir=0x43baee,
        resource_dir@entry=0x7ffff7fe6200, rsrc_data=0x7ffff7fe6200 "", rsrc_tree_level=0, type=0x0,
        id=0x2c000, language=language@entry=0x7ffffffdd9a0, type_string=type_string@entry=0x0,
        name_string=name_string@entry=0x0, lang_string=lang_string@entry=0x0,
        callback=callback@entry=0x41d000 <pe_collect_resources>,
        callback_data=callback_data@entry=0x708bb0) at modules/pe.c:485
    #6  0x000000000041cd5d in pe_iterate_resources (pe=pe@entry=0x708bb0,
        callback=callback@entry=0x41d000 <pe_collect_resources>,
        callback_data=callback_data@entry=0x708bb0) at modules/pe.c:571
    #7  0x000000000041ded3 in pe_parse_header (pe=pe@entry=0x708bb0, base_address=0,
        flags=<optimized out>) at modules/pe.c:1232
    #8  0x000000000041fb92 in pe__load (context=0x7fffffffe020, module_object=0x70b3b0,
        module_data=<optimized out>, module_data_size=<optimized out>) at modules/pe.c:2080
    #9  0x00000000004098b8 in yr_modules_load (module_name=0x706199 "pe",
        context=context@entry=0x7fffffffe020) at modules.c:164
        #10 0x000000000042b550 in yr_execute_code (rules=rules@entry=0x704280,
        context=context@entry=0x7fffffffe020, timeout=timeout@entry=1000000,
        start_time=start_time@entry=1429135627) at exec.c:755
    #11 0x0000000000414d50 in yr_rules_scan_mem_blocks (rules=rules@entry=0x704280,
        block=<optimized out>, block@entry=0x7fffffffe0d0, flags=flags@entry=0,
        callback=callback@entry=0x4045f0 <callback>, user_data=user_data@entry=0x7fffffffe670,
        timeout=timeout@entry=1000000) at rules.c:425
    #12 0x0000000000414ed9 in yr_rules_scan_mem (timeout=1000000, user_data=0x7fffffffe670,
        callback=0x4045f0 <callback>, flags=0, buffer_size=<optimized out>, buffer=<optimized out>,
        rules=0x704280) at rules.c:515
    #13 yr_rules_scan_file (rules=0x704280, filename=<optimized out>, flags=0,
        callback=callback@entry=0x4045f0 <callback>, user_data=0x7fffffffe670, timeout=1000000)
        at rules.c:540
    #14 0x0000000000402ee5 in main (argc=<optimized out>, argv=0x7fffffffe358) at yara.c:1043

**Comment by wxsBSD** [comment]
I believe there is an open PR for this already.

**Comment by plusvic** [comment]
Fixed in aa0f6c43548414c103beac651add0ec23c9e0253
