### ISSUE TITLE
Conditions don't handle empty string comparison

### ISSUE THREAD

**Issue by gljiva** [plusvic/yara#303]
I'm unable to express condition for empty section names. For example following condition gives error:
pe.sections[0].name == ""
Error:
pack.yara(5): error: empty string

Checking the name yara extracts from sample it looks correct, all sections have 0 len name.
yr_object_set_string field[sections[%i].name] len[0]
yr_object_set_string field[sections[%i].name] len[0]
yr_object_set_string field[sections[%i].name] len[0]
yr_object_set_string field[sections[%i].name] len[0]
yr_object_set_string field[sections[%i].name] len[0]
yr_object_set_string field[sections[%i].name] len[0]

How can I express empty section name condition? Is there a way to call len(sections[x].name)?

**Comment by plusvic** [comment]
Fixed in commit d90463455d91855cb040bd1d291fd25ee6aa71cf

**Comment by jascoet-mwb** [comment]
Hey, I'm facing the same issue again (Yara 4.2.3, but possibly witht the latest as well) where empty section names are not matching. 
How do I match this ?
`pe.sections[0].name == ""`

**Comment by jascoet-mwb** [comment]
@plusvic I see you made a fix, does this fix apply to pe module ?
