### ISSUE TITLE
can't import yara-python on OSX

### ISSUE THREAD

**Issue by blacktop** [plusvic/yara#317]
If I install it from pip (version 1.7) it works, but doesn't have features like yara.compile(error_on_warning)

I installed yara with brew on my Mac and installed yara-python from your yara 3.3.0 release.

```bash
Python 2.7.10 (default, May 26 2015, 13:01:57) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/user/.virtualenvs/osiris-env/lib/python2.7/site-packages/yara.so, 2): Symbol not found: _yr_rules_load_stream
  Referenced from: /Users/user/.virtualenvs/osiris-env/lib/python2.7/site-packages/yara.so
  Expected in: flat namespace
 in /Users/user/.virtualenvs/osiris-env/lib/python2.7/site-packages/yara.so
```

**Comment by blacktop** [comment]
This was fixed by installing yara from souce, there is something wrong with the brew formula, it is probably storing important files in places where the yara-python code can't find them.

**Comment by wxsBSD** [comment]
I think @sroberts is responsible for that. May want to bring it up with him.

**Comment by blacktop** [comment]
This works if I use --system-site-packages when invoking my virtualenv.

**Comment by Grazfather** [comment]
The issue is apparently partially because the yara recipe installs the python module -- Maybe it shouldn't. This is an issue for both people who use venvs and those that use python three.
