### ISSUE TITLE
Errors using module in offset search

### ISSUE THREAD

**Issue by gljiva** [plusvic/yara#319]
On of the examples in documentation is:
`$a in (entrypoint..entrypoint + 10)`
Entrypoint has been replaced with pe.entry_point, but using something like:
`$a in (pe.entry_point..pe.entry_point + 10)`
returns:
`: error: syntax error, unexpected '.', expecting _IDENTIFIER_`

Looks like anything containing dots isn't allowed so things like following also fails:
`$pattern in (pe.sections[pe.section_index(".data")].raw_data_offset..(pe.sections[pe.section_index(".data")].raw_data_offset + pe.sections[pe.section_index(".data")].raw_data_size))`

Is there a workaround or a better way to look for a pattern in a specific section?

**Comment by plusvic** [comment]
Fixed in 7a4f9f5985d5f64127c2cda179f426751cfe3a0e
