### ISSUE TITLE
memory-mapped file access can lead to crash due to uncaught exception/signal

### ISSUE THREAD

**Issue by hillu** [plusvic/yara#321]
Yara crashes on Windows and Linux systems while scanning files that cannot be read due to filesystem corruption: The memory mapping operation (CreateFileMapping()+MapViewOfFile() or mmap()) was successful, but an exception (Windows: EXCEPTION_IN_PAGE_ERROR, Unix: SIGBUS) is thrown as soon as data that cannot be read from disk is accessed. This is documented behavior -- see [Reading and Writing From a File View](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366801%28v=vs.85%29.aspx) and the mmap(2) manpage. In my opinion, libyara should catch those errors because how files are accessed is an implementation detail that the user does not need to be concerned with.

On Unix systems, it is possible to trigger SIGBUS by truncating the file while yara is scanning. I have also been able to trigger EXCEPTION_ACCESS_VIOLATION (instead of EXCEPTION_IN_PAGE_ERROR) in a yara process running under Wine by doing the same. I have not yet found an easy way to trigger this problem on a "real" Windows system.

**Comment by hillu** [comment]
In the meantime, I have found a way to reproduce the problem on Windows: If a removable volume (such as a CD-ROM drive) is removed while yara is scanning a large file on that volume, it will crash.

**Comment by plusvic** [comment]
Fixed in db22ffda588b9b3abc619f8a2f616d0be57e9335
