### ISSUE TITLE
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule

### ISSUE THREAD

**Issue by gowenfawr** [plusvic/yara#326]
I have been trying to get Yara running on RedHat and am getting the following error:

`AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule`

I got this on RHEL 6, which was a shoddy platform anyway because it's glibc was too old.  So I spun up a RHEL 7 machine and built fresh from tarball and am still seeing the issue.

Demonstrated using yara-ctypes:

    $ yara-ctypes -h
    Traceback (most recent call last):
    File "/usr/bin/yara-ctypes", line 7, in <module>
        from yara.cli import entry
    File "/usr/lib/python2.7/site-packages/yara/__init__.py", line 7, in <module>
        from yara.rules import compile
    File "/usr/lib/python2.7/site-packages/yara/rules.py", line 17, in <module>
        from yara.libyara_wrapper import *
    File "/usr/lib/python2.7/site-packages/yara/libyara_wrapper.py", line 362, in <module>
        libyaradll.lookup_rule.restype = POINTER(RULE)
    File "/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
        func = self.__getitem__(name)
    File "/usr/lib64/python2.7/ctypes/__init__.py", line 378, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule
    $

Demonstrated using Volatility 2.4:

    $ ./vol.py --info
    Volatility Foundation Volatility Framework 2.4
    *** Failed to import volatility.plugins.linux.malfind (AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule)
    *** Failed to import volatility.plugins.dumpcerts (AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule)
    *** Failed to import volatility.plugins.mac.mac_yarascan (AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule)
    *** Failed to import volatility.plugins.ssdt (AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule)
    *** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)

This system has glibc-2.18 and python-2.7.5.

Is there anything I can to to resolve this issue?  Is there anything I can do to help debug this issue?

Any pointers appreciated!

Thanks
gowenfawr

**Comment by plusvic** [comment]
Mmm, it seems that you are installing a recent version of yara but yara-ctypes is out of date and expects an older version. Which version of yara are you using?

**Comment by gowenfawr** [comment]
Yara is 3.4.0 (and I simply cannot believe I didn't put that in the initial report - sorry!)

I just re-scanned the install docs and I did miss the step for building and installing the yara-python extension in the 3.4.0 source tree.  I performed those steps, and to be uptight did `pip uninstall  yara` and `pip install yara`, and now get a different error:

    $ yara-ctypes
    Traceback (most recent call last):
      File "/bin/yara-ctypes", line 7, in <module>
        from yara.cli import entry
    ImportError: libyara.so.3: cannot open shared object file: No such file or directory

This appears to be because the yara-python build creates /usr/lib64/python2.7/site-packages/yara.so but the libraries installed by yara itself are under /usr/lib (non-64).

    $ ll /usr/lib/libyara*
    -rw-r--r--. 1 root root 553186 Jun 30 14:44 /usr/lib/libyara.a
    -rwxr-xr-x. 1 root root    924 Jun 30 14:44 /usr/lib/libyara.la
    lrwxrwxrwx. 1 root root     16 Jun 30 14:44 /usr/lib/libyara.so -> libyara.so.3.4.0
    lrwxrwxrwx. 1 root root     16 Jun 30 14:44 /usr/lib/libyara.so.3 -> libyara.so.3.4.0
    -rwxr-xr-x. 1 root root 318883 Jun 30 14:44 /usr/lib/libyara.so.3.4.0
    $ ll /usr/lib64/libyara*
    ls: cannot access /usr/lib64/libyara*: No such file or directory
    $

strace output shows that it is indeed enumerating all the lib64 possibilities for finding libyara.so.3 but not the regular lib:

    open("/lib64/tls/x86_64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/lib64/tls/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/lib64/x86_64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/lib64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/tls/x86_64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/tls/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/x86_64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/libyara.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    write(2, "libyara.so.3: cannot open shared"..., 71) = 71

Did I do something wrong to end up with the two portions of the install under different lib trees?  The 3.4.0 base build was a simple 'configure --prefix=/usr' and the yara-python build was the simple `python setup.py build; sudo python setup.py install` described in the documentation

**Comment by plusvic** [comment]
Let me clarify.... there are two different ways of using yara from Python: yara-ctypes and yara-python, and you seem to be mixing them. The official one is yara-python (and I believe that Volatility 2.4 is using it). In the other hand yara-ctypes is not part of the official yara, it's a library created and maintained by someone else. The problem is that they created a PIP package called yara, which install yara-ctypes, and this is probably a source of confusion. Furthermore, yara-ctypes seems to be abandoned because according to their documentation (https://pypi.python.org/pypi/yara) the latest version was created for yara 1.7.7.

In resume:

* Uninstall yara-ctypes with: pip uninstall yara
* Install yara-python with: 

```
cd yara-python
python setup.py build
sudo python setup.py install
```
yara-python comes in the source code tarball.

**Comment by gowenfawr** [comment]
Thank you - that resolves the problem.  I'm not sure where I got the idea that yara-ctypes was also required, but that's what was kicking me in the pants.  After following your instructions Volatility is running without errors.

Thank you!!!
