### ISSUE TITLE
C1047 error when compiling as release on windows with Vis 2012

### ISSUE THREAD

**Issue by chrisddom** [plusvic/yara#327]
Hi,

 I'm compiling 3.4 with VS2012 and I'm getting the same error as described at http://blog.gmane.org/gmane.comp.security.yara.general/month=20140801

 It seems ok if it's just the debug build. Looking at the old ticket, I might need to rebuild jansson32.lib separately?

 Separately - When testing I've noticed my compiled version of 3.3 with full optimisation seems to be far slower than the official release. Are you compiling with VS or another compiler?

Thanks!

**Comment by plusvic** [comment]
I'm using Visual Studio 2010, and yes, you'll need to rebuild probably both jansson32.lib and libeay32.lib in order to get solve this problem.

**Comment by chrisddom** [comment]
Thanks for the quick reply - will do
