### ISSUE TITLE
Segfault in yr_arena_load_stream

### ISSUE THREAD

**Issue by andy11** [plusvic/yara#328]
I found a few more segfaults with AFL, but I think they're all hitting on the same area in yr_arena_load_stream. 

Tested with commit: be2c1b8081d80c3710de8e28d72a7b77343898db

$ hexdump ./crash.yara 
0000000 4159 4152 0003 0000 5208 0141 0000 7700
0000010

$ yara ./crash.yara ./
ASAN:SIGSEGV
=================================================================
==21206==ERROR: AddressSanitizer: SEGV on unknown address 0x60207700eff0 (pc 0x00000042c7a4 bp 0x60800000bfd8 sp 0x7fff198f9f30 T0)
    #0 0x42c7a3 in yr_arena_load_stream (/home/xxx/yara+0x42c7a3)
    #1 0x4179a7 in yr_rules_load (/home/xxx/yara+0x4179a7)
    #2 0x403086 in main (/home/xxx/yara+0x403086)
    #3 0x7fe3afaea78f in __libc_start_main (/usr/lib/libc.so.6+0x2078f)
    #4 0x403678 in _start (/home/xxx/yara+0x403678)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 yr_arena_load_stream
==21206==ABORTING

**Comment by plusvic** [comment]
Fixed in 15d249b4d58b496e485c4f8da5f1b4de799d6608
