### ISSUE TITLE
How to retrieve list of rules referenced in a rule

### ISSUE THREAD

**Issue by jhere** [plusvic/yara#329]
I'm unsure if this is the appropriate place to ask, however in the C library I'm having a bit of trouble finding a way to determine which rules are being referenced by any particular rule. Essentially I am referring to rules referenced in the condition block. 

If there is a way to perform this operation (or a direction toward implementing it) I'd appreciate a response.

**Comment by wxsBSD** [comment]
I've tried to do similar in the past, and it requires significant changes. Conditions are compiled down to byte code and the actual "string" which is the condition is discarded. You would have to take each token in the condition and operate on that.

**Comment by jhere** [comment]
Thank you for the prompt response.
