### ISSUE TITLE
Hex Strings With Wildcards All Null Under "YR_STRING->string"

### ISSUE THREAD

**Issue by jhere** [plusvic/yara#330]
I am unsure if I simply am making a mistake, however while iterating over the rules: 

YR_RULE *head = rules->rules_list_head;
YR_STRING *string;
while(!RULE_IS_NULL(head)) {
yr_rule_strings_foreach(head, string) {
if (STRING_IS_HEX(string) {
//string->string is null if it contains a wildcard such as {35 a? f2 ??}
}
}
head++;
}

Thanks.

**Comment by plusvic** [comment]
Yes, that's correct, string->string will be NULL for any string containing wildcards. Only fixed strings like {35 A1}, {FA BA DA}, "foo", "bar", etc will have a non-NULL string field.

**Comment by jhere** [comment]
Sorry, how do we go about retrieving wildcard containing strings in this case?

**Comment by plusvic** [comment]
Those can't be retrieved from the compiled rules, they are stored as opcodes for the regular expression engine.
