### ISSUE TITLE
Yara python install on windows does not work

### ISSUE THREAD

**Issue by scudette** [plusvic/yara#342]
When installing the yara-python package from https://b161268c3bf5a87bc67309e7c870820f5f39f672.googledrive.com/host/0BznOMqZ9f3VUek8yN3VvSGdhRFU/

I installed the yara-python-3.4.0.win-amd64-py2.7.exe file which added the python modules to site-packages, but when trying to import yara it fails:

```
C:\>c:\Python27\python.exe
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
>>> ^Z
```

It is not clear to me where I can get this dll. The binary yara-3.4.0-win64.zip seems to only contain a binary yara64.exe. Is there a distribution of the dll for windows?

**Comment by plusvic** [comment]
The missing DLL is probably MSVCR100.DLL. This should be solved by installing the Visual C++ 2010 redistributable package. You get it here: https://www.microsoft.com/en-us/download/details.aspx?id=14632

**Comment by scudette** [comment]
Ok thanks, this solves the issue. A more helpful error message would be good but Im on my way now!

Thanks again.
