### ISSUE TITLE
[Feature] Real Virtual Addresses of String Matches in Process Scans

### ISSUE THREAD

**Issue by jhumble** [plusvic/yara#349]
It would be highly useful to get back the actual virtual addresses of matches for process scans. Currently, the string offsets returned seems to be just the offsets into the current block being scanned, but the address of the block itself is absent.

As far as I can tell, the block structure being passed around in the code does have an address member, it would just need to be pushed into the string tuple returned to python. If it were, we could do all kinds of interesting things like leveraging psutil.memory_maps to identify which loaded library or section of memory a match occurred in.

**Comment by wxsBSD** [comment]
Looks like yara does this already, but yara-python does not. I've got a branch which should fix it, though I have not tested on anything that scans in more than one block. Would you be willing to try out the add_base branch from https://github.com/wxsBSD/yara-python? If you would rather apply the patch locally for testing it is available here: https://github.com/plusvic/yara-python/compare/master...wxsBSD:add_base

**Comment by jhumble** [comment]
Thanks! I'll be giving this a try as soon as I figure out how to build yara.pyd on Windowss

**Comment by plusvic** [comment]
@wxsBSD your solution is correct, submit the PR and I'll merge your patch.

**Comment by wxsBSD** [comment]
In another conversation it was brought to my attention that https://github.com/VirusTotal/yara-python/pull/1 (which I think addresses this, it's been too long to remember exactly) never got merged.
