### ISSUE TITLE
Build broken on OS X 10.11 and xcode 7.0.1

### ISSUE THREAD

**Issue by wxsBSD** [plusvic/yara#351]
This is more an FYI for others, and I am working on it. I updated my laptop to 10.11 last night, and also updated to xcode 7.0.1. According to this link http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html, Apple has finally killed off the OpenSSL headers in their latest xcode. They still ship the libraries but no longer ship headers. This breaks the build for obvious reasons.

It sounds like the right fix is to use brew provided openssl, which will be required now. I'll be working on an update to that.

**Comment by Neo23x0** [comment]
I started downloading El Capitan this morning and stopped the download when
I saw this list of Apps not working on 10.11:

http://forums.macrumors.com/threads/os-x-el-capitan-working-not-working-apps.1890772/

Even the nightly build of LittleSnitch seems to be broken. I wouldn't
recommend an upgrade yet.
God knows what happens to my NTFS drivers, TrueCrypt and other less known
and supported software.



On Thu, Oct 1, 2015 at 9:55 AM, Wesley Shields <notifications@github.com>
wrote:

> This is more an FYI for others, and I am working on it. I updated my
> laptop to 10.11 last night, and also updated to xcode 7.0.1. According to
> this link
> http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html,
> Apple has finally killed off the OpenSSL headers in their latest xcode.
> They still ship the libraries but no longer ship headers. This breaks the
> build for obvious reasons.
>
> It sounds like the right fix is to use brew provided openssl, which will
> be required now. I'll be working on an update to that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plusvic/yara/issues/351>.
>



-- 
Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

PGP Key:
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM
Key ID:
FE04247D50D1ACC855CB FD26 19E9 BF9E 78C1  D582 FE04 247D 50D1 ACC8
