### ISSUE TITLE
Limiting CPU Usage

### ISSUE THREAD

**Issue by chrisddom** [plusvic/yara#358]
Hi quick question - apologies if this isn't the correct place-

Is there a way, or anything on the roadmap, to limit CPU usage with Yara?

If not I'll look at wrapping it with something like http://mion.faireal.net/BES/ before execution.

Thanks!

**Comment by Neo23x0** [comment]
I use the yara-python module in THOR and allow throttling of the scan
process by adding short sleeps every X directory walk elements.
This way the scan takes longer but single core CPU systems don't get the
full load and other processes can step in and perform their tasks.
I also set the priority/nice of the scan process to the lowest value
available. (depending on Windows/Linux OS)

On Fri, Oct 16, 2015 at 8:08 AM, chrisddom <notifications@github.com> wrote:

> Hi quick question - apologies if this isn't the correct place-
>
> Is there a way, or anything on the roadmap, to limit CPU usage with Yara?
>
> If not I'll look at wrapping it with something like
> http://mion.faireal.net/BES/ before execution.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plusvic/yara/issues/358>.
>



-- 
Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

PGP Key:
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM
Key ID:
FE04247D50D1ACC855CB FD26 19E9 BF9E 78C1  D582 FE04 247D 50D1 ACC8

**Comment by plusvic** [comment]
If you're scanning a directory you can try lowering the number of scanning threads with --threads=X command-line argument (the default is 8 threads). With a single thread, even if YARA takes 100% of one CPU core, you should have plenty of processing power with the remaining cores (assuming you have a multi-core CPU, which is the standard nowadays)

**Comment by hillu** [comment]
For the command line, `nice(1)` (Unix) and the START built-in (Windows) should be helpful.

For using libyara on Windows, I have done this successfully using `SetPriorityClass()` and/or `SetThreadPriority()`.
