### ISSUE TITLE
error: unknown module "hash"

### ISSUE THREAD

**Issue by Dx3webs** [plusvic/yara#367]
I have suddenly started to get this error (after downloading and compiling the same way on the same servers)

**Comment by plusvic** [comment]
That's probably because you don't have openssl installed and the hash module depends on openssl. Try this:

./configure --with-crypto

**Comment by Dx3webs** [comment]
that was my 1st thought.. I reinstalled with the above settings but to no avail

**Comment by twpDone** [comment]
I had the same problem, installing libssl-dev fixed it for me.

As specified in the issue [363]( https://github.com/plusvic/yara/issues/363)

> Please mention: libssl-dev for openssl (--with-crypto) flag
> This is for debian/ubuntu and derivative systems. 

Maybe yara should use the non-dev version or specify  libssl-dev as requirement.

**Comment by Dx3webs** [comment]
recompiling after installing libssl-dev did the trick here also
thanks
