### ISSUE TITLE
Unable to handle a PE file packed with SimplePack

### ISSUE THREAD

**Issue by Chandlr** [plusvic/yara#371]
file: 
https://mega.nz/#!0dsWlDDC!ZCOLtBhrVohRdl10AHn5NjdGwKYTF0kdc9dzJVg4SeA

rule SimplePack1XMethod2bagie
{
      meta:
		author="_pusher_"
		date = "2015-11"
strings:
		$a0 = { 4D 5A 90 EB 01 00 52 E9 ?? 01 00 00 50 45 00 00 4C 01 02 00 00 00 00 00 00 00 00 00 00 00 00 00 E0 00 0F 03 0B 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0C 00 00 00 00 ?? ?? ?? 00 10 00 00 00 02 00 00 01 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 }

condition:
		//it cannot load the PE properly so it fails to check imports
		//pe.imports ("kernel32.dll","LoadLibraryA") and
		//pe.imports ("kernel32.dll","GetProcAddress") and
		//pe.imports ("kernel32.dll","VirtualProtect") and
		$a0 at 0
}

**Comment by wxsBSD** [comment]
This one is because we can't get the imports from this binary because it is packed. We attempt to get the offset for the first import which is at RVA 0x154, which has no valid offset in the packed binary. Not much we can do here, I think.

**Comment by Chandlr** [comment]
ah ok

**Comment by hillu** [comment]
Ero Carrera's `python-pefile` sees the three imports:

<pre>
----------Imported symbols----------

[IMAGE_IMPORT_DESCRIPTOR]
0x400      0x0   OriginalFirstThunk:            0x0       
0x400      0x0   Characteristics:               0x0       
0x404      0x4   TimeDateStamp:                 0x0        [Thu Jan  1 00:00:00 1970 UTC]
0x408      0x8   ForwarderChain:                0x0       
0x40C      0xC   Name:                          0x154     
0x410      0x10  FirstThunk:                    0x68028   

KERNEL32.DLL.LoadLibraryA Hint[0]
KERNEL32.DLL.GetProcAddress Hint[0]
KERNEL32.DLL.VirtualProtect Hint[0]
</pre>
