### ISSUE TITLE
Another Entrypoint bug FSG2.0

### ISSUE THREAD

**Issue by Chandlr** [plusvic/yara#379]
sample:
https://mega.nz/#!RQcEVIJA!o1ArlIwnCB1ynrRdzirpl-34eMxLZeyAXbfA3j6u6Iw

this should work but doest:

rule FSG200 : bart xt
{
      meta:
		author="_pusher_"
		date = "2015-11"
strings:
		$a0 = { 4B 45 52 4E 45 4C 33 32 2E 64 6C 6C 00 }
		$a1 = { 46 53 47 21 }
condition:
		($a0 at 0x1F2) and ($a1 at 0x14) and (pe.entry_point == 154)
}

**Comment by wxsBSD** [comment]
I suspect you wanted to say ```pe.entry_point == 0x154```. The entry point as specified in the file is 0x154 but YARA is unable to find the file offset which contains that RVA.

I also can not get this sample to execute.

**Comment by wxsBSD** [comment]
I'm wondering if it makes sense to have a ```pe.raw_entry_point``` which is the entry point as specified in the file before going through ```pe_rva_to_offset()```.

**Comment by Chandlr** [comment]
Do you have some antivirus causing issues ?
Maybe Win10 or something.. dont know why this and DEF should't work.
Yeh i meant to have 0x154
here is the sig i use:

rule FSG200 : bart xt
{
	meta:
		author="_pusher_"
		date = "2015-11"
	strings:
		//if this is modified its not really FSG is it ?
		$a0 = { 4B 45 52 4E 45 4C 33 32 2E 64 6C 6C 00 }
	condition:
					//Time_Date_Stamp
		($a0 at 0x1F2) and (pe.timestamp == 0x21475346) and (pe.entry_point == 0x154)
}

**Comment by hillu** [comment]
OllyDbg 2 (Windows XP) thinks that the EP is at 0x00400154 which matches 0x154 into the file. Just like in #395, YARA does not assign an entry point because 0x154 is not inside any section.
