### ISSUE TITLE
Returning ERROR_WRONG_ARGUMENTS in some cases?

### ISSUE THREAD

**Issue by wxsBSD** [plusvic/yara#381]
Someone recently contacted me about YARA returning an internal error (40). I investigated and this turned out to be what is going on:

The rule in question:

```
wxs@wxs-mbp yara % cat test.sig
import "math"

rule foo {
  condition:
    math.in_range(math.entropy(filesize - 1048576, filesize), 7.0, 9.0)
}
```

If you feed this a file which is less than 1MB you get the error:

```
wxs@wxs-mbp yara % ls -l /bin/ls
-rwxr-xr-x  1 root  wheel  38512 Dec  2 22:36 /bin/ls*
wxs@wxs-mbp yara % ./yara test.sig /bin/ls
error scanning /bin/ls: internal error: 40
wxs@wxs-mbp yara %
```

Error 40 is ERROR_WRONG_ARGUMENTS, which comes from here (libyara/modules/math.c):

```
  if (offset < 0 || length < 0 || offset < context->mem_block->base)
    return ERROR_WRONG_ARGUMENTS;
```

Since this causes YARA to immediately return does it make sense to ```return_float(UNDEFINED)``` instead? I thought about looking for underflow in OP_INT_SUB (and related operators, and also for overflow in the ADD and MUL operators) but am not sure if it is the right thing to do compared to leaving it up to the modules to check for bad values. I suspect leaving it up to the modules is the right thing to do since the virtual machine can't really tell what the result of the operator will be used for.

Given all that, do you think you would accept a diff to cause the math module to ```return_float(UNDEFINED)``` in the cases where the arguments are impossible to operate on? At least this would cause the situation described above not to error out on a file less than 1MB.

**Comment by plusvic** [comment]
Yes, I agree with you. Returning ```return_float(UNDEFINED)``` in those cases is the best approach. Submit the PR and I'll merge it.
