### ISSUE TITLE
Compiled rulesets can no longer be used across 32/64 bit architectures.

### ISSUE THREAD

**Issue by hillu** [plusvic/yara#389]
Commit 3f1cbf2a6bf2a962a71173e3ffb8a7d076b6523e added `pragma pack(8)` to `yara/types.h`, affecting many of the structures that are written to and read from disk by (yarac, `yr_rules_load*`, `yr_rules_save*`). It turns out that now structures are laid out differently on 32 and 64 bit Linux which is probably not what was intended. Needless to say, this causes problems when trying to load compiled rules on that have been generated on a different architecture. (At least on i386/amd64 this used to work.)

According to the gcc documentation, `#pragma pack(N)` specifies a maximum alignment. I'm not sure what happens here -- apparently gcc won't pick alignments larger than 4 byte for i386.

This can be fixed by specifying explicit alignments for every struct member: `__attribute__((aligned(8)))`.

**Comment by hillu** [comment]
In 933dd39ca42cbe319e49f2dbb2afbdfed426967e I have committed a test program that tries to document the current offsets as produced by gcc 5.3.1 on Debian/unstable for amd64. I'll try to come up iwith an alternative to the `pack` pragma that does not seem to be able to produce exact alignments.

**Comment by plusvic** [comment]
Fixed in 094309bc06ede17de3c04ca08e01ca2522c8c73b
