### ISSUE TITLE
magic module segfaults when magic_buffer (from libmagic) returns NULL

### ISSUE THREAD

**Issue by gregcopenhaver** [plusvic/yara#397]
The functions magic_type and magic_mime_type from the "magic" module both call magic_buffer from libmagic (http://www.darwinsys.com/file/), and then call return_string with this result.  magic_buffer can return NULL in some cases, but this is not checked in magic_type, magic_mime_type, or return_string.  return_string calls strlen, which will segfault if the argument is NULL.

magic_mime_type from libyara/modules/magic.c (also see magic_type):
```c
define_function(magic_mime_type)
{
...
  if (cached_mime_types[context->tidx] == NULL)
  {
...
    cached_mime_types[context->tidx] = magic_buffer(
        magic_cookie[context->tidx],
        block->data,
        block->size);
  }

  return_string((char*) cached_mime_types[context->tidx]);
}
```

return_string from libyara/include/yara/modules.h:
```c
#define return_string(string) { \
      assertf( \
          __function_obj->return_obj->type == OBJECT_TYPE_STRING, \
          "return type differs from function declaration"); \
      char* s = (char*) (string); \
      yr_object_set_string( \
          (s != (char*) UNDEFINED) ? s : NULL, \
          (s != (char*) UNDEFINED) ? strlen(s) : 0, \
          __function_obj->return_obj, \
          NULL); \
      return ERROR_SUCCESS; \
    }
```

magic_buffer from libmagic:
```c
public const char *
magic_buffer(struct magic_set *ms, const void *buf, size_t nb)
{
	if (ms == NULL)
		return NULL;
	if (file_reset(ms) == -1)
		return NULL;
	/*
	 * The main work is done here!
	 * We have the file name and/or the data buffer to be identified.
	 */
	if (file_buffer(ms, -1, NULL, buf, nb) == -1) {
		return NULL;
	}
	return file_getbuffer(ms);
}
```

Two possible ways to fix:
1. return_string could be changed to handle NULL
2. magic_mime_type and magic_type could check if cached_mime_types[context->tidx] is NULL and if so, call return_string(UNDEFINED);

**Comment by plusvic** [comment]
This was a very detailed bug report. Thank you!
Fixed in commit 3c74c9bc3a73de8b09a12ef1c43f7cbe72722c82
