### ISSUE TITLE
Yara segfaults when matching on a string dictionary item that doesn't exist

### ISSUE THREAD

**Issue by Professor-plum** [plusvic/yara#405]
If a key doesn't exist inside a modules's string dictionary variable and a rule tests for it using a regex expression yara segfaults.

Only crashes with "matches" key word.  "Contains" doesn't have the same effect

The attached rule will reproduce the crash
[test.txt](https://github.com/plusvic/yara/files/138818/test.txt)

**Comment by hillu** [comment]
I can reproduce the segmentation fault with 3.4.0, but not with the current trunk. A quick test with `git bisect` shows it was fixed in 65a86115524c453f6bc4719781321ae99ac25b0f.

**Comment by plusvic** [comment]
Thanks for the triage job @hillu. I think we can close this issue.
