### ISSUE TITLE
Yara doesn't allow negative integers in meta fields

### ISSUE THREAD

**Issue by Professor-plum** [plusvic/yara#406]
This may be intended behavior, but if so please document it.
 meta fields cannot be negative values.

The attached rule will not compile
[test.txt](https://github.com/plusvic/yara/files/138824/test.txt)

**Comment by hillu** [comment]
Are you seeing something like `syntax error, unexpected '-', expecting _NUMBER_ or _TEXT_STRING_ or _TRUE_ or _FALSE_`? This looks like an oversight in the lexer to me -- the  underlying datatype in `_YR_META` is an `int64_t`.

Cheers,
-Hilko

**Comment by Professor-plum** [comment]
Yes, that's exactly the error I'm seeing, I also believe it is an oversight. Thanks for looking up the signedness of the underlying type.
