### ISSUE TITLE
Configure file won't work. Sytnax error.

### ISSUE THREAD

**Issue by aarud** [plusvic/yara#416]
./configure.ac: line 1: syntax error near unexpected token `[yara],'
./configure.ac: line 1: `AC_INIT([yara], [3.4.0], [vmalvarez@virustotal.com])'

**Comment by kallanreed** [comment]
You need automake, autoconf, and libtool to build. See #363

**Comment by tamsec** [comment]
All three are already installed.

**Comment by aarud** [comment]
All three are already installed.
