### ISSUE TITLE
whitelist.yara(10): error: undefined identifier "hash"

### ISSUE THREAD

**Issue by blade1989** [plusvic/yara#426]
While running `yara -r ./malwares.yara /home/USER/www`, I got the following error:

> whitelist.yara(10): error: undefined identifier "hash"
> whitelist.yara(27): error: undefined identifier "hash"
> whitelist.yara(63): error: undefined identifier "hash"
> whitelist.yara(72): error: undefined identifier "hash"
> whitelist.yara(92): error: undefined identifier "hash"
> whitelist.yara(116): error: undefined identifier "hash"
> whitelist.yara(129): error: undefined identifier "hash"
> whitelist.yara(138): error: undefined identifier "hash"
> whitelist.yara(152): error: undefined identifier "hash"
> whitelist.yara(163): error: undefined identifier "hash"
> whitelist.yara(170): error: undefined identifier "Symfony"
> ./malwares.yara(71): error: invalid regular expression "$too_many_chr": syntax error, unexpected '?', expecting $end
> ./malwares.yara(129): error: undefined identifier "IsWhitelisted"
> ./malwares.yara(188): error: undefined identifier "IsWhitelisted"
> ./malwares.yara(251): error: undefined identifier "IsWhitelisted"
> ./malwares.yara(283): error: undefined identifier "IsWhitelisted"

I have complete rights to scan in it, if that the problem:

```
sudo chown -R USER:USER /home/USER/www
sudo chmod -R 775 /home/USER/www
```

**Comment by plusvic** [comment]
That's probably because you didn't had OpenSSL installed while building YARA.

**Comment by blade1989** [comment]
@plusvic didn't read the readme properly. As is stated in php-malware-finder bug report,  `...you need yara 3.4.0...`. My apologize!

**Comment by plusvic** [comment]
Ok, then I close this issue.

**Comment by liqingjia** [comment]
Windows(exe) need to install OpenSSL ?

**Comment by plusvic** [comment]
@liqingjia do mean if OpenSSL is required to build YARA in Windows? Or if the pre-built Windows binary require that OpenSSL is installed? The answer to the first question is yes, and for the second one is no. The pre-built binary is statically linked with OpenSSL.

**Comment by liqingjia** [comment]
https://github.com/VirusTotal/yara/releases/tag/v4.3.0      
this releases version is statically linked with OpenSSL? but undefined identifier "hash".
how to get pre-built binary(statically linked with OpenSSL)

**Comment by liqingjia** [comment]
![企业微信截图_168075263484](https://user-images.githubusercontent.com/12861709/230266898-98ea3305-ca26-40c1-b7d6-e1f13da055eb.png)
is this pre-built binary? this exe looks like is not statically linked with OpenSSL.

**Comment by liqingjia** [comment]
import "hash"  must be use.
my apologize!
