### ISSUE TITLE
pe: RVA calculation still seems not quite right.

### ISSUE THREAD

**Issue by hillu** [plusvic/yara#429]
The following rule should match for the sample with md5=7c45366b9ba885e1b19e9ffeb7f614b4, but it does not.

    rule VirusShare_7c45366b9ba885e1b19e9ffeb7f614b4 {
    condition:
        pe.imports("KERNEL32.dll", "LoadLibraryA") and
        pe.imports("KERNEL32.dll", "GetProcAddress")
    }

Apparently, rounding sections to File Alignment is not correct, in this case FileAlignment = SectionAlignment = 0x1000 whereas PointerToRawData for the relevant section = 0x200...

**Comment by plusvic** [comment]
Fixed in 6bbbdc2a510871534aa0d2860c46f46415642107
