### ISSUE TITLE
hope yara can support regular expression ruler for backreferences

### ISSUE THREAD

**Issue by weiyiling** [plusvic/yara#457]
I hope yara can support regular expression ruler for backreferences, how can i do? Contact with me @ hzy@weiyiling.cn, thank you!

**Comment by plusvic** [comment]
Unfortunately backreferences can't be implemented in an efficient way, that's why YARA doesn't support them. For more details take a look at: http://stackoverflow.com/questions/4076687/regular-expressions-with-on-and-backreferences-support

**Comment by weiyiling** [comment]
@plusvic Thank you for your reply anyway！I guessed that as your answer, but I still have some strong need to use yara's regular expression with backreferences, I wonder if I can use perl lib or re2 lib or any other lib to implement.If you have some good suggestion, please favour me with your instructions, thank you very much again!
